MENU_RES = (MENU_WIDTH, MENU_HEIGHT) = (800, 700)
GRID_CELL_SIZE = 20
GRID_SIZE = (GRID_W, GRID_H) = (MENU_WIDTH // GRID_CELL_SIZE, MENU_HEIGHT // GRID_CELL_SIZE)
TANGRAM_SIDE_LENGTH = 280
TANGRAM_AREA = TANGRAM_SIDE_LENGTH ** 2
PIECE_ROTATION = 45
MIN_DIST_BETWEEN_TWO_CORNERS = 5
MIN_SUB_PUZZLE_AREA = .8 * ((TANGRAM_SIDE_LENGTH / 2) * (TANGRAM_SIDE_LENGTH / 4)) // 2 # area of the small triangle
